export const faces = {
    HEART: 'heart', 
    SPADE: 'spade', 
    CLUB: 'club', 
    DIAMOND:'diamond'
};

export const cards = {A: 'A', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', J: 'J', Q: 'Q', K: 'K'};

export default {
    1: {face: faces.SPADE, card: cards.A},
    2: {face: faces.SPADE, card: cards[2]},
    3: {face: faces.SPADE, card: cards[3] },
    4: {face: faces.SPADE, card: cards[4] },
    5: {face: faces.SPADE, card: cards[5] },
    6: {face: faces.SPADE, card: cards[6] },
    7: {face: faces.SPADE, card: cards[7] },
    8: {face: faces.SPADE, card: cards[8] },
    9: {face: faces.SPADE, card: cards[9] },
    10: {face: faces.SPADE, card: cards[10] },
    11: {face: faces.SPADE, card: cards.J },
    12: {face: faces.SPADE, card: cards.Q },
    13: {face: faces.SPADE, card: cards.K },
    14: {face: faces.HEART, card: cards.A },
    15: {face: faces.HEART, card: cards[2] },
    16: {face: faces.HEART, card: cards[3] },
    17: {face: faces.HEART, card: cards[4] },
    18: {face: faces.HEART, card: cards[5] },
    19: {face: faces.HEART, card: cards[6] },
    20: {face: faces.HEART, card: cards[7] },
    21: {face: faces.HEART, card: cards[8] },
    22: {face: faces.HEART, card: cards[9] },
    23: {face: faces.HEART, card: cards[10] },
    24: {face: faces.HEART, card: cards.J },
    25: {face: faces.HEART, card: cards.Q },
    26: {face: faces.HEART, card: cards.K },
    27: {face: faces.DIAMOND, card: cards.A },
    28: {face: faces.DIAMOND, card: cards[2] },
    29: {face: faces.DIAMOND, card: cards[3] },
    30: {face: faces.DIAMOND, card: cards[4] },
    31: {face: faces.DIAMOND, card: cards[5] },
    32: {face: faces.DIAMOND, card: cards[6] },
    33: {face: faces.DIAMOND, card: cards[7] },
    34: {face: faces.DIAMOND, card: cards[8] },
    35: {face: faces.DIAMOND, card: cards[9] },
    36: {face: faces.DIAMOND, card: cards[10] },
    37: {face: faces.DIAMOND, card: cards.J },
    38: {face: faces.DIAMOND, card: cards.Q },
    39: {face: faces.DIAMOND, card: cards.K },
    40: {face: faces.CLUB, card: cards.A },
    41: {face: faces.CLUB, card: cards[2] },
    42: {face: faces.CLUB, card: cards[3] },
    43: {face: faces.CLUB, card: cards[4] },
    44: {face: faces.CLUB, card: cards[5] },
    45: {face: faces.CLUB, card: cards[6] },
    46: {face: faces.CLUB, card: cards[7] },
    47: {face: faces.CLUB, card: cards[8] },
    48: {face: faces.CLUB, card: cards[9] },
    49: {face: faces.CLUB, card: cards[10] },
    50: {face: faces.CLUB, card: cards.J },
    51: {face: faces.CLUB, card: cards.Q },
    52: {face: faces.CLUB, card: cards.K },
};