export const faces = {
    HEART: 'heart', 
    SPADE: 'spade', 
    CLUB: 'club', 
    DIAMOND:'diamond'
};

export const cards = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
export const priority = ['2', '3', '4', '5', '6', '7', '8', '9', '10','J', 'Q', 'K', 'A'];

export default {
    1: {face: faces.SPADE, card: cards[0]},
    2: {face: faces.SPADE, card: cards[1]},
    3: {face: faces.SPADE, card: cards[2] },
    4: {face: faces.SPADE, card: cards[3] },
    5: {face: faces.SPADE, card: cards[4] },
    6: {face: faces.SPADE, card: cards[5] },
    7: {face: faces.SPADE, card: cards[6] },
    8: {face: faces.SPADE, card: cards[7] },
    9: {face: faces.SPADE, card: cards[8] },
    10: {face: faces.SPADE, card: cards[9] },
    11: {face: faces.SPADE, card: cards[10] },
    12: {face: faces.SPADE, card: cards[11] },
    13: {face: faces.SPADE, card: cards[12] },
    14: {face: faces.HEART, card: cards[0] },
    15: {face: faces.HEART, card: cards[1] },
    16: {face: faces.HEART, card: cards[2] },
    17: {face: faces.HEART, card: cards[3] },
    18: {face: faces.HEART, card: cards[4] },
    19: {face: faces.HEART, card: cards[5] },
    20: {face: faces.HEART, card: cards[6] },
    21: {face: faces.HEART, card: cards[7] },
    22: {face: faces.HEART, card: cards[8] },
    23: {face: faces.HEART, card: cards[9] },
    24: {face: faces.HEART, card: cards[10] },
    25: {face: faces.HEART, card: cards[11] },
    26: {face: faces.HEART, card: cards[12] },
    27: {face: faces.DIAMOND, card: cards[0] },
    28: {face: faces.DIAMOND, card: cards[1] },
    29: {face: faces.DIAMOND, card: cards[2] },
    30: {face: faces.DIAMOND, card: cards[3] },
    31: {face: faces.DIAMOND, card: cards[4] },
    32: {face: faces.DIAMOND, card: cards[5] },
    33: {face: faces.DIAMOND, card: cards[6] },
    34: {face: faces.DIAMOND, card: cards[7] },
    35: {face: faces.DIAMOND, card: cards[8] },
    36: {face: faces.DIAMOND, card: cards[9] },
    37: {face: faces.DIAMOND, card: cards[10] },
    38: {face: faces.DIAMOND, card: cards[11] },
    39: {face: faces.DIAMOND, card: cards[12] },
    40: {face: faces.CLUB, card: cards[0] },
    41: {face: faces.CLUB, card: cards[1] },
    42: {face: faces.CLUB, card: cards[2] },
    43: {face: faces.CLUB, card: cards[3] },
    44: {face: faces.CLUB, card: cards[4] },
    45: {face: faces.CLUB, card: cards[5] },
    46: {face: faces.CLUB, card: cards[6] },
    47: {face: faces.CLUB, card: cards[7] },
    48: {face: faces.CLUB, card: cards[8] },
    49: {face: faces.CLUB, card: cards[9] },
    50: {face: faces.CLUB, card: cards[10] },
    51: {face: faces.CLUB, card: cards[11] },
    52: {face: faces.CLUB, card: cards[12] },
};