export const faces = {
    HEART: 'heart', 
    SPADE: 'spade', 
    CLUB: 'club', 
    DIAMOND:'diamond'
};

export const cards = {A: 'A', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', J: 'J', Q: 'Q', K: 'K'};

export default {
    1: {face: faces.SPADE, card: cards.A, img: import('./img/1.png') },
    2: {face: faces.SPADE, card: cards[2], img: import('./img/2.png') },
    3: {face: faces.SPADE, card: cards[3], img: import('./img/3.png') },
    4: {face: faces.SPADE, card: cards[4], img: import('./img/4.png') },
    5: {face: faces.SPADE, card: cards[5], img: import('./img/5.png') },
    6: {face: faces.SPADE, card: cards[6], img: import('./img/6.png') },
    7: {face: faces.SPADE, card: cards[7], img: import('./img/7.png') },
    8: {face: faces.SPADE, card: cards[8], img: import('./img/8.png') },
    9: {face: faces.SPADE, card: cards[9], img: import('./img/9.png') },
    10: {face: faces.SPADE, card: cards[10], img: import('./img/10.png') },
    11: {face: faces.SPADE, card: cards.J, img: import('./img/11.png') },
    12: {face: faces.SPADE, card: cards.Q, img: import('./img/12.png') },
    13: {face: faces.SPADE, card: cards.K, img: import('./img/13.png') },
    14: {face: faces.HEART, card: cards.A, img: import('./img/14.png') },
    15: {face: faces.HEART, card: cards[2], img: import('./img/15.png') },
    16: {face: faces.HEART, card: cards[3], img: import('./img/16.png') },
    17: {face: faces.HEART, card: cards[4], img: import('./img/17.png') },
    18: {face: faces.HEART, card: cards[5], img: import('./img/18.png') },
    19: {face: faces.HEART, card: cards[6], img: import('./img/19.png') },
    20: {face: faces.HEART, card: cards[7], img: import('./img/20.png') },
    21: {face: faces.HEART, card: cards[8], img: import('./img/21.png') },
    22: {face: faces.HEART, card: cards[9], img: import('./img/22.png') },
    23: {face: faces.HEART, card: cards[10], img: import('./img/23.png') },
    24: {face: faces.HEART, card: cards.J, img: import('./img/24.png') },
    25: {face: faces.HEART, card: cards.Q, img: import('./img/25.png') },
    26: {face: faces.HEART, card: cards.K, img: import('./img/26.png') },
    27: {face: faces.DIAMOND, card: cards.A, img: import('./img/27.png') },
    28: {face: faces.DIAMOND, card: cards[2], img: import('./img/28.png') },
    29: {face: faces.DIAMOND, card: cards[3], img: import('./img/29.png') },
    30: {face: faces.DIAMOND, card: cards[4], img: import('./img/30.png') },
    31: {face: faces.DIAMOND, card: cards[5], img: import('./img/31.png') },
    32: {face: faces.DIAMOND, card: cards[6], img: import('./img/32.png') },
    33: {face: faces.DIAMOND, card: cards[7], img: import('./img/33.png') },
    34: {face: faces.DIAMOND, card: cards[8], img: import('./img/34.png') },
    35: {face: faces.DIAMOND, card: cards[9], img: import('./img/35.png') },
    36: {face: faces.DIAMOND, card: cards[10], img: import('./img/36.png') },
    37: {face: faces.DIAMOND, card: cards.J, img: import('./img/37.png') },
    38: {face: faces.DIAMOND, card: cards.Q, img: import('./img/38.png') },
    39: {face: faces.DIAMOND, card: cards.K, img: import('./img/39.png') },
    40: {face: faces.CLUB, card: cards.A, img: import('./img/40.png') },
    41: {face: faces.CLUB, card: cards[2], img: import('./img/41.png') },
    42: {face: faces.CLUB, card: cards[3], img: import('./img/42.png') },
    43: {face: faces.CLUB, card: cards[4], img: import('./img/43.png') },
    44: {face: faces.CLUB, card: cards[5], img: import('./img/44.png') },
    45: {face: faces.CLUB, card: cards[6], img: import('./img/45.png') },
    46: {face: faces.CLUB, card: cards[7], img: import('./img/46.png') },
    47: {face: faces.CLUB, card: cards[8], img: import('./img/47.png') },
    48: {face: faces.CLUB, card: cards[9], img: import('./img/48.png') },
    49: {face: faces.CLUB, card: cards[10], img: import('./img/49.png') },
    50: {face: faces.CLUB, card: cards.J, img: import('./img/50.png') },
    51: {face: faces.CLUB, card: cards.Q, img: import('./img/51.png') },
    52: {face: faces.CLUB, card: cards.K, img: import('./img/52.png') },
};